User can view a list of booster packs.
ALee-DF/weiss-schwarz-deck-builder pull request #16
Opened 2017-09-12 22:25 UTC by ALee-DF

![screen shot 2017-09-12 at 3 24 19 pm](https://user-images.githubusercontent.com/31448956/30351069-78da5a6c-97ce-11e7-97b2-ba484f291871.png)

2017-09-12 23:07 UTC, thebearingedge requested changes
1. Generate your booster pack elements using JavaScript. Model the data in objects and define a function that renders them.
2. Rename files to use `kebab-case`.
3. Commit to a background color/image and soften it compared to the foreground items.
4. Make your list items bigger.
5. Use poster graphics instead of box images.
![list-of-booster-packs](https://user-images.githubusercontent.com/7432943/30352406-8b7e13f6-97d4-11e7-8b17-76329e171c54.png)

2017-09-13 07:54 UTC, ALee-DF commented
![screen shot 2017-09-13 at 12 52 20 am](https://user-images.githubusercontent.com/31448956/30365884-094b63a8-981e-11e7-8c53-b0cc2a33ee6e.png)

2017-09-13 17:04 UTC, thebearingedge requested changes
Ok, _much_ better! See if you can get an evenly distributed amount of space between your booster pack tiles. I have a couple of code review notes too.

2017-09-13 17:04 UTC, thebearingedge commented on deck-builder/index.html
> +    <div id="booster-packs-section">
It would be more semantic to use a `section` element with an `id` of `booster-packs`.

2017-09-13 17:04 UTC, thebearingedge commented on deck-builder/main.js
> +function renderPack(packObject) {
It's best to omit technical jargon from your variable names. `pack` should suffice instead of `packObject`.

2017-09-13 17:04 UTC, thebearingedge commented on deck-builder/main.js
> +  $newCover.alt = packObject.name
If your element represents a "cover", you can just name it `$cover`. Same with `$pack`.

2017-09-13 18:39 UTC, ALee-DF commented
![screen shot 2017-09-13 at 11 39 22 am](https://user-images.githubusercontent.com/31448956/30394546-38ef2a5e-9878-11e7-82c5-ccb81350c847.png)

2017-09-13 21:02 UTC, thebearingedge approved these changes
YEASS!

2017-09-13 21:19 UTC, ALee-DF commented
![screen shot 2017-09-13 at 2 18 55 pm](https://user-images.githubusercontent.com/31448956/30401283-87ca223a-988e-11e7-8f23-ba4a2f37b3c5.png)

2017-09-13 22:10 UTC, merged